### ISSUE TITLE
[BUG] Installing error

### ISSUE THREAD

**Issue by franciscorosso** [fermoya/cocoapods-catalyst-support#28]
I am getting error after installing cocoapods-catalyst-support on my M1 Mac.

I tried `sudo gem install cocoapods-catalyst-support`.  The gem installs OK, but then when I want to run `pod catalyst init` I got this error `[!] Unknown command: catalyst`

Thanks in advance for your help,
Francisco.

**Comment by gracedmarks** [comment]
I experienced bug like this too

**Comment by luca992** [comment]
Same. Did you ever resolve it?

**Comment by luca992** [comment]
Figured it out:

First add this [Gemfile](https://github.com/fermoya/cocoapods-catalyst-support/blob/master/Sample/Gemfile) to the root of you project:

Run 
`bundle install`

`bundle exec pod catalyst init`

So I guess you need to prepend `bundle exec` to your pod commands
