### ISSUE TITLE
Certain files are not downloaded in certain Cocoapods.

### ISSUE THREAD

**Issue by jkichline** [fermoya/cocoapods-catalyst-support#30]
**Describe the bug**
It appears that certain Cocoapods and configurations that work on Intel Macs do not pod update on M1 Macs. In both cases, a single file in a specific Cocoapod is not able to be downloaded which prevents the project from compiling. In this case "libxlsxwriter" will not download metadata.h/.m using the 1.1.1 version, but will if dropped to 1.0.9. Additionally if that works,  then GoogleAPIClientForREST/Drive will not download GTLRQuery.h

**Podfile**
```
require 'cocoapods-catalyst-support'

# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

abstract_target 'All' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OnSong
	pod 'GoogleAPIClientForREST/Drive' #, '~> 1.2.1'
	pod 'MZFormSheetPresentationController'
	pod 'FMDB'
	pod 'NMSSH'
	pod 'GoogleSignIn'
	pod 'MHWDirectoryWatcher'
	pod 'libxlsxwriter'
	pod 'GTMNSStringHTMLAdditions'
	pod 'Purchases' #, '= 3.7.1'
	pod 'XMLDictionary'
	pod 'AirTurnInterface'
	pod 'GCDWebServer'
	pod 'GCDWebServer/WebDAV'
	pod 'MMDrawerController', '~> 0.5.7'
	#pod 'google-cast-sdk'
	
	target 'OnSong' do
	end
	
	target 'OnSong Pro' do
	end
	
	target 'OnSong 2021' do
	end
	
	target 'OnSong 2021 Beta' do
	end
end

# Configure your macCatalyst dependencies
catalyst_configuration do
	# Uncomment the next line for a verbose output
	verbose!
	ios 'GoogleSignIn' #, '4.0.1'
	ios 'NMSSH'

	# ios '<pod_name>' # This dependency will only be available for iOS
	# macos '<pod_name>' # This dependency will only be available for macOS
end

post_install do |installer|
	installer.configure_catalyst
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
        end
    end
end
```

**Environment**
* `cocoapods-catalyst-support` => 0.1.3
* _Ruby_ version [e.g 2.6.0] => ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
* _Cocoapods_ version [e.g 1.10.0] => 1.10.1
* _Xcode_ version [e.g 12.2] => Build version 13A5192j

**Additional context**

**Comment by fermoya** [comment]
This sounds as an issue on their end, especially `libxlsxwriter`. If those `pods` aren't affected by the script I don't see why they'd fail.

I can't reproduce it so I'll close
