### ISSUE TITLE
Why did this go from being a script to a library to install? 

### ISSUE THREAD

**Issue by thecavilnator** [fermoya/cocoapods-catalyst-support#37]
This used to be a script and now it's an entire library. Why has this occurred? Is the install safe?

**Comment by fermoya** [comment]
Yes, it's easier to maintain as it grows with new functionality and covers more scenarios. Plus, it's easier to use now and more verbose.

Feel free to keep using the script if you wish

**Comment by fermoya** [comment]
Yes, it's easier to maintain as it grows with new functionality and covers more scenarios. Plus, it's easier to use now and more verbose.

Feel free to keep using the script if you wish
