### ISSUE TITLE
Library seems very insecure.

### ISSUE THREAD

**Issue by thecavilnator** [fermoya/cocoapods-catalyst-support#38]
The library has a ton of modules and sdks linked to it and seems VERY sketchy.

**Comment by fermoya** [comment]
I don't understand what you mean by modules. It's gone from a couple-of-hundreds-of-lines script to a proper Ruby gem where the script is distributed into several files. It can be installed via a `gem install command` and offers a cli commands to help you start using it.

I appreciate your feedback but the future there's no way back to a 1 file
